### ISSUE TITLE
Payment - bad request

### ISSUE THREAD

**Issue by AlbertoIT** [QuantozTechnology/csharp-stellar-base#13]
Hi,

im trying to call  Payment(KeyPair from, KeyPair to, long amount)  
from csharp-stellar-base/src/Examples/Program.cs in the test net.

But it seems to end up always in a bad request.
I already made sure the receiving account was funded and the sender had enough XLM.

Any advice?

**Comment by AlbertoIT** [comment]
My fault, keypair was not properly created :)

**Comment by cc5985** [comment]
I have the same problem..

but it was OK with the official horizon server , but on my server , it returns a 400 bad request....
I am screwed!

help!
