### ISSUE TITLE
Creating Non asset - Issue Facing.

### ISSUE THREAD

**Issue by safeerk** [QuantozTechnology/csharp-stellar-base#21]
Dear Kindly help on it , am not sure whats the issue on this.
 `     All the timeam getting Bad request message, also am new to this also...
 

            var myKeyPair = KeyPair.FromSeed("SCZANGBA5YHTNYVVV4C3U252E2B6P6F5T3U6MM63WBSBZATAQI3EBTQ4");

            var myReceiverPair = KeyPair.FromSeed("SC4CGETADVYTCR5HEAVZRB3DZQY5Y4J7RFNJTRA6ESMHIPEZUSTE2QDK");

            Asset assetBHD = new Asset("EUROOSNET", myKeyPair);
          

            Account ReceiverAcc = new Account(myReceiverPair, GetSequence(myReceiverPair.Address), 0);

            Transaction allowAstroDollars = new Transaction.Builder(ReceiverAcc)
            .AddOperation( new ChangeTrustOperation.Builder(assetBHD, 1000).Build())
            .Build();

            allowAstroDollars.Sign(myReceiverPair);

            var tx1 = allowAstroDollars.ToEnvelopeXdrBase64();

            var response1 = PostResult(tx1);
             

            Account IssuerAcc = new Account(myKeyPair, GetSequence(myKeyPair.Address), 0);

            Transaction sendAstroDollars = new Transaction.Builder(IssuerAcc)
           .AddOperation(  new PaymentOperation.Builder(myReceiverPair, assetBHD, 10).Build())
           .Build();

            sendAstroDollars.Sign(myKeyPair);

            var tx2 = sendAstroDollars.ToEnvelopeXdrBase64();

            var response2 = PostResult(tx2);   `

**Comment by mvaneijk** [comment]
Hi, with the badrequest message, you also get an error code and explanation. Do you have enough Lumen on the accounts to create these transactions for example?

You might want to try your transaction first using the Stellar laboratory: https://www.stellar.org/laboratory/ and see what the results are.

**Comment by safeerk** [comment]
Thanks man, from laboratory I have created test accounts and put lumens on it.

For native am able to do load lumens , but the above is custom asset.. which I face issue.
Thanks

**Comment by safeerk** [comment]
I think the issue which i think is like i need to create a account with custom Asset , On the stellar laboratory there is any work around to create that and to load amount on it.?

Thanks..

**Comment by mvaneijk** [comment]
I would advice you to visit the stellar slack for general support on transactions.
https://slack.stellar.org

I may help you if you post the error message you are receiving

**Comment by safeerk** [comment]
![image](https://user-images.githubusercontent.com/22815639/35215077-4312e36e-ff74-11e7-831e-1acf7f87c847.png)

Please find the error message which am getting. Also can you please let me know am correct on the way for creating custom asset(EG: USD, BANANA, GOAT etcc..) not stellar lumens.

1. Create account - From laboraory i have created account which i can load lumens only.. How i will acheive creating custom asset account ?
2. From laboratory can i change the custom asset from Lumens to custom asset(EG: USD, BANANA, GOAT etcc..) ?

Hope its clear.. THanks .

Regards
S

**Comment by mvaneijk** [comment]
Can you post your txEnvelopes (tx1 and tx2) ?

**Comment by safeerk** [comment]
HI @mvaneijk  , Sorry for the delay.
Please find the below txEnvelops... Looking for your coreration on this:

tx1: AAAAAGPEGa6b9z+K6UZF7UoqRggkTeNPdbr8R4nLC3X8tuAnAAAAZABluuUAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAYAAAACVVNEQUJDAAAAAAAAjQYNBGPxV6UHQGdrzY/Zcn5AEFpKr5G9w0prDcPM8wUAAAAAAAAD6AAAAAAAAAAB/LbgJwAAAECwURlvmyrw8GMz5qY2RemrPgm6UU1/LqYWoIq6k86bWi7sYbyki4nSU4LgfmLB3foStDXY6sco/2StZSYvSpsK

tx2: AAAAAI0GDQRj8VelB0Bna82P2XJ+QBBaSq+RvcNKaw3DzPMFAAAAZABlutcAAAAMAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAY8QZrpv3P4rpRkXtSipGCCRN4091uvxHicsLdfy24CcAAAACVVNEQUJDAAAAAAAAjQYNBGPxV6UHQGdrzY/Zcn5AEFpKr5G9w0prDcPM8wUAAAAAAAAACgAAAAAAAAABw8zzBQAAAEDSYkb5jN+Vbw28FVkUnnPaFg99Mm1+eG50RTg25jl3UOd+ONYyBN3YlkkknVS0Ps6HFv0/f0rC4y4PXC8BE9cO
